djangoform/djangoform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reviews.urls'))
]

djangoform/reviews/urls.py
from django.urls import path
from . import views
app_name = 'reviews'
urlpatterns = [
    path('create',views.AddView.as_view(),name='home'),
    path('success',views.SuccessView.as_view(),name='success'),
    path('update/<int:pk>',views.EditView.as_view(),name='update'),
    path('display',views.DispView.as_view(),name='list'),
    path('details/<int:pk>',views.DataView.as_view(),name='details'),
    path('delete/<int:pk>',views.DropView.as_view(),name='delete')
    # path('<int:pk>',views.update)

]

djangoform/reviews/models.py
from django.db import models

# Create your models here.
class review(models.Model):
    username = models.CharField( max_length=50)
    feedback = models.TextField()
    ratings = models.IntegerField()
    favourite_color = models.CharField( max_length=20,blank=True)

    def __str__(self):
        return self.username

djangoform/reviews/forms.py
from django import forms
from .models import review

# choice = [
#     ('1','Blue'),``
#     ('2','Red'),
#     ('3','Green'),
#     ('4','Yellow')
# ]

# class ReviewForm(forms.Form):
#     username = forms.CharField(label="Your Name : ",max_length=10,error_messages={'required':'Form Cannot Be Empty'})
#     feedback = forms.CharField(label="Feed Back : ",max_length=250,widget=forms.Textarea)
#     ratings = forms.IntegerField(label="Ratings : ")
#     favourite_color = forms.MultipleChoiceField( label="Favourite Color : ",choices=choice,widget=forms.CheckboxSelectMultiple) . 


class ReviewForm(forms.ModelForm):
    class Meta:
        model = review
        fields = "__all__"
        exclude = ['favourite_color']
        labels = {'username':'Your Name','feedback':'Your Review'}
        error_messages = {
            'username':{'required':'User Name cannot be empty','max_lengt':'Limit Exceeded'}
        }

djangoform/reviews/views.py
from typing import Any
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . forms import ReviewForm
from . models import review
from django.views.generic import View,TemplateView,UpdateView,ListView,DetailView,DeleteView
from django.views.generic.edit import DeleteView


# Create your views here.

# def home(request):

#     if request.method == "POST":
#         un = request.POST['username']
#         if un == '':
#             return render(request,'reviews/home.html',{'error':True})
#         print(un)
#         return HttpResponse('Thank You')
#     return render(request,'reviews/home.html',{'error':False})

# def home(request):

#     if request.method == "POST":
#         a = ReviewForm(request.POST)
#         a.save()
#         return HttpResponse('Thank You')
        
#     else:
#         a= ReviewForm()
#     return render(request,'reviews/home.html',{'form':a})


# def update(request,pk):
#     if request.method == "POST":
#         data =review.objects.get(id = pk)
#         a = ReviewForm(request.POST,instance = data)
#         a.save()
#         return HttpResponse('Update Successful')
#     else:
#         a = ReviewForm()
#     return render(request,'reviews/home.html',{'form':a})

class AddView(View):
    def get(self,request):
        a= ReviewForm()
        return render(request,'reviews/home.html',{'form':a})
        

    def post(self,request):
            a = ReviewForm(request.POST)
            a.save()
            return redirect('reviews:success')
    

class SuccessView(TemplateView):
    template_name = "reviews/success.html"

    def get_context_data(self, **kwargs: Any):
        context =  super().get_context_data(**kwargs)
        context["message"] = "Data Stored Successfully to Database Table"
        return context


class EditView(UpdateView):
    template_name = 'reviews/home.html'
    model = review
    fields =['username','feedback','ratings']
    success_url = '/create'


class DispView(ListView):
    model = review
    template_name = 'review/list.html'

class DataView(DetailView):
    model = review
    template_name = 'reviews/details.html'


class DropView(DeleteView):
    model = review
    template_name = 'reviews/delete.html'
    success_url = '/display'


     

  

djangoform/reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title> {% block title %}{% endblock title %} </title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

djangoform/reviews/templates/reviews/delete.html
{% extends "reviews/base.html" %}

{% block content %}
<form method = "POST">
    {% csrf_token %}
    <center>
        <h3 style = "color:red"> Delete Task </h3>
        <h5> Are You Sure <b> {{object}} </b> ? </h5>
        <input type = "submit" value ="Delete">
        <a href={% url "reviews:list" %}>Cancel</a>
    </center>
</form>

{% endblock content %}

djangoform/reviews/templates/reviews/details.html
{% extends "reviews/base.html" %}

{% block content %}

<center>
    <ul>
        <li> Username : {{object.username}} </li>
        <li> Feedback : {{object.feedback}} </li>
        <li> Ratings  : {{object.ratings}} </li>
    </ul>
</center>

{% endblock content %}

djangoform/reviews/templates/reviews/home.html
{% extends "reviews/base.html" %}

{% block title %}HOME{% endblock title %}

{% block content %}
<form action="" method = "post">
    {% csrf_token %}
    {% comment %} <label for="username">User Name:</label>
    <input type="text" name="username"> {% endcomment %}
    {% for i in form  %}

    {{i.label}}
    {{i}}
    {{i.errors}}<br> <br>
    
    {% endfor %}
    

    <input type="submit">
    {% comment %} {% if error %}
        <h4 style = "color:red"> Form Cannot be empty, Please fill the data </h4>
    
    {% endif %}{% endcomment %}






</form>

{% endblock content %}

djangoform/reviews/templates/reviews/list.html
{% extends "reviews/base.html" %}

{% block content%}

<ul>
    {% for i in object_list  %}

    <li><a href = "{% url "reviews:details" i.id %}">{{i.username}}</a> <a href = "{% url "reviews:delete" i.id %}">Delete</a></li>
    
    {% endfor %}
{% endblock content %}

djangoform/reviews/templates/reviews/success.html
{% extends "reviews/base.html" %}

{% block content %}
<center>

    <h1> Thank You </h1>
    <h1> {{message}} </h1> 
</center>
{% endblock content %}